// One-off: download the web fonts locally so CrickSim is fully offline.
// Fetches each font CSS with a modern UA (to get woff2), downloads every
// woff2 into css/fonts/, and emits css/fonts.css with clean local @font-face
// rules (woff2 only, remote fallbacks stripped).
import { mkdir, writeFile, rm } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const FONT_DIR = path.join(ROOT, "css", "fonts");
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";

const SOURCES = [
  "https://api.fontshare.com/v2/css?f[]=clash-display@500,600,700&f[]=satoshi@400,500,700&display=swap",
  "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@500;700;800&display=swap",
];

await rm(FONT_DIR, { recursive: true, force: true });
await mkdir(FONT_DIR, { recursive: true });

let out = "/* Self-hosted fonts for offline PWA use. Generated by tools/fetch-fonts.mjs */\n";
let files = 0;

for (const url of SOURCES) {
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
  for (const block of css.match(/@font-face\s*\{[^}]*\}/g) || []) {
    // first woff2 url (may be protocol-relative //cdn... or https://...)
    const m = block.match(/url\(\s*['"]?((?:https:)?\/\/[^)'"]+\.woff2)['"]?\s*\)/);
    if (!m) continue;
    const woff2Url = m[1].startsWith("//") ? "https:" + m[1] : m[1];
    const buf = Buffer.from(await (await fetch(woff2Url, { headers: { "User-Agent": UA } })).arrayBuffer());

    const fam = (block.match(/font-family:\s*['"]?([^;'"]+?)['"]?\s*;/) || [, "Font"])[1].trim();
    const style = (block.match(/font-style:\s*([a-zA-Z]+)/) || [, "normal"])[1];
    const wt = (block.match(/font-weight:\s*([0-9]+(?:\s+[0-9]+)?)/) || [, "400"])[1].trim();
    const ur = block.match(/unicode-range:\s*([^;}]+)/);

    const slug = fam.toLowerCase().replace(/\s+/g, "-");
    const hash = createHash("sha1").update(woff2Url).digest("hex").slice(0, 6);
    const fname = `${slug}-${wt.replace(/\s+/g, "_")}-${hash}.woff2`;
    await writeFile(path.join(FONT_DIR, fname), buf);
    files++;

    out += `@font-face{font-family:'${fam}';font-style:${style};font-weight:${wt};font-display:swap;src:url("fonts/${fname}") format("woff2");${ur ? `unicode-range:${ur[1].trim()};` : ""}}\n`;
  }
}

await writeFile(path.join(ROOT, "css", "fonts.css"), out);
console.log(`Wrote css/fonts.css with ${files} woff2 files into css/fonts/`);
